#!/bin/bash

if [ "$#" -lt 1 ]
then
  echo ""
  echo "Git add, commit and push Kang's CV"
  echo ""
  echo "Usage:    $0 <commit>"
  echo "<commit>: (input) the commit content"
  echo ""
  exit -1;
fi

echo "Current path is `pwd`"
git add .
git commit -m "$1"
git push
